/**
 * Copies the ABI of every frontend-facing contract from the Hardhat artifacts
 * directory into `lib/web3/abi/<Contract>.ts` as a typed `as const` array.
 *
 * Why `.ts` and not `.json`: viem/wagmi infer function names, argument and
 * return types from a *literal* ABI type. A JSON import is widened to
 * `{ type: string; ... }[]`, which loses all of that and forces casts at every
 * call site. A generated `as const` module keeps the ABI committed (so the
 * Next.js build on Vercel never touches `artifacts/`) *and* fully typed.
 *
 * This runs automatically after `npx hardhat compile` (see hardhat.config.ts)
 * and can be run on its own with `npx hardhat run scripts/syncAbis.ts`.
 */
import * as fs from "fs"
import * as path from "path"

/** Contracts whose ABI the frontend imports. Keep in sync with lib/web3/abis.ts. */
export const FRONTEND_CONTRACTS = [
  "MatDAO_Escrow",
  "MatDAO_IPNFT",
  "MatDAO_Swap",
  "MockUSDC",
  "MockIPT",
  "SwapRouter",
] as const

export type FrontendContractName = (typeof FRONTEND_CONTRACTS)[number]

export function artifactPath(artifactsDir: string, name: FrontendContractName): string {
  return path.join(artifactsDir, "contracts", `${name}.sol`, `${name}.json`)
}

export function readArtifactAbi(artifactsDir: string, name: FrontendContractName): unknown[] {
  const file = artifactPath(artifactsDir, name)
  if (!fs.existsSync(file)) {
    throw new Error(`Artifact not found for ${name}: ${file}. Run \`npx hardhat compile\` first.`)
  }
  const artifact = JSON.parse(fs.readFileSync(file, "utf8")) as { abi?: unknown[] }
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Artifact for ${name} has no "abi" array: ${file}`)
  }
  return artifact.abi
}

export function renderAbiModule(name: FrontendContractName, abi: unknown[]): string {
  const json = JSON.stringify(abi, null, 2)
  return [
    `// AUTO-GENERATED by scripts/syncAbis.ts from artifacts/contracts/${name}.sol/${name}.json`,
    `// Do not edit by hand - run \`npm run hh:compile\` to regenerate.`,
    ``,
    `export const ${name}_ABI = ${json} as const`,
    ``,
  ].join("\n")
}

/**
 * Writes one module per contract. Returns the list of files that changed.
 */
export function syncAbis(artifactsDir: string, outDir: string): string[] {
  fs.mkdirSync(outDir, { recursive: true })
  const changed: string[] = []
  for (const name of FRONTEND_CONTRACTS) {
    const abi = readArtifactAbi(artifactsDir, name)
    const target = path.join(outDir, `${name}.ts`)
    const next = renderAbiModule(name, abi)
    const prev = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null
    if (prev !== next) {
      fs.writeFileSync(target, next)
      changed.push(target)
    }
  }
  return changed
}

// Allow `npx hardhat run scripts/syncAbis.ts` / `ts-node scripts/syncAbis.ts`.
if (require.main === module) {
  const root = path.resolve(__dirname, "..")
  const written = syncAbis(path.join(root, "artifacts"), path.join(root, "lib", "web3", "abi"))
  console.log(written.length ? `Updated:\n  ${written.join("\n  ")}` : "ABIs already up to date.")
}
